language: cpp

os:
    - linux
    - osx
    - windows

compiler:
    - clang
    - gcc

install:

before_script:
    - if [ $TRAVIS_OS_NAME = windows ]; then choco install make; fi

script:
    - cd src
    - make
    - make test
    - make clean
    - make cov
